version: '3.8'

services:
  keycloak:
    image: jboss/keycloak:latest
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/realm-export.json:/opt/jboss/keycloak/standalone/configuration/realm-export.json
    command:
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=singleFile"
      - "-Dkeycloak.migration.file=/opt/jboss/keycloak/standalone/configuration/realm-export.json"
      - "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING"

  flask-app:
    build:
      context: ./flask-app
    ports:
      - "5000:5000"
    depends_on:
      - keycloak
    environment:
      - KEYCLOAK_URL=http://keycloak:8080/auth
      - KEYCLOAK_REALM=myrealm
      - KEYCLOAK_CLIENT_ID=myclient
      - KEYCLOAK_CLIENT_SECRET=mysecret
      - FLASK_ENV=development

networks:
  default:
    driver: bridge